#!/bin/bash

source ./env

$PACKAGES/tmux
$PACKAGES/discord
$PACKAGES/vscode
$PACKAGES/docker
$PACKAGES/spotify
$PACKAGES/caprine
$PACKAGES/keepassx
$PACKAGES/zsh
$PACKAGES/vim
$PACKAGES/dropbox
$PACKAGES/google-chrome
$PACKAGES/telegram
$PACKAGES/slack
$PACKAGES/postman
$PACKAGES/nvidia-drivers
$PACKAGES/golang
$PACKAGES/mailspring
#$PACKAGES/nvm

