#!/bin/bash

PACKAGE_NAME=$1
PACKAGE_MANAGER=$2
PACKAGE_MANAGER_FLAGS=$3

echo " "
echo "Installing $PACKAGE_NAME ----------------------------"

# Checking if package is already installed
if check_installation $PACKAGE_NAME; then
  echo "No action required"
  return 0
fi

# Pick requested package manager and install package
if [ $PACKAGE_MANAGER = "apt" ]; then
  apt-get install $PACKAGE_NAME $PACKAGE_MANAGER_FLAGS
elif [ $PACKAGE_MANAGER = "snap" ]; then
  snap install $PACKAGE_MANAGER_FLAGS $PACKAGE_NAME
else
  echo "$PACKAGE_MANAGER is not a known package manager"
fi

# Validate installation
if check_installation $PACKAGE_NAME; then
  echo "Installation successful"
  return 0
else
  echo "Installation failed"
  return 1
fi

check_installation() {
  PACKAGE_NAME=$1
  
  if type $PACKAGE_NAME >/dev/null 2>&1; then
    return 0
  else
    return 1
  fi
}
